apiVersion: v1
kind: ConfigMap
metadata:
  name: commondb-sts-configmap
  namespace: 5gc-commondb-sts
data:

  primary.cnf: |
    [mariadb]
    log-bin                         # enable binary logging
    log-basename=my-mariadb         # used to be independent of hostname changes (otherwise is in datadir/mysql)
    innodb_flush_log_at_trx_commit=2
    max_prepared_stmt_count=30000
    connect_timeout=36000
    #lower_case_table_names=1

  primary-sts-0.sql: |
    CREATE USER 'repluser0'@'%' IDENTIFIED BY 'replsecret0';
    GRANT REPLICATION REPLICA ON *.* TO 'repluser0'@'%';
    CREATE DATABASE primary_sts_0_db;
    # We have to know name of sts (`mariadb-sts`) and 
    # service `mariadb-service` in advance as an FQDN.
    # No need to use master_port
    CHANGE MASTER TO 
    MASTER_HOST='commondb-sts-1.commondb.5gc-commondb-sts.svc.cluster.local',
    MASTER_USER='repluser1',
    MASTER_PASSWORD='replsecret1',
    MASTER_CONNECT_RETRY=10;

  primary-sts-1.sql: |
    CREATE USER 'repluser1'@'%' IDENTIFIED BY 'replsecret1';
    GRANT REPLICATION REPLICA ON *.* TO 'repluser1'@'%';
    CREATE DATABASE primary_sts_1_db;
    # We have to know name of sts (`mariadb-sts`) and 
    # service `mariadb-service` in advance as an FQDN.
    # No need to use master_port
    CHANGE MASTER TO 
    MASTER_HOST='commondb-sts-0.commondb.5gc-commondb-sts.svc.cluster.local',
    MASTER_USER='repluser0',
    MASTER_PASSWORD='replsecret0',
    MASTER_CONNECT_RETRY=10;
