apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: commondb-sts
  namespace: 5gc-commondb-sts
spec:
  serviceName: "commondb"
  replicas: 2
  selector:
    matchLabels:
      app: commondb
  template:
    metadata:
      labels:
        app: commondb
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-commondb
        image: private.el:5000/mariadb:latest
        imagePullPolicy: Always
        command:
        - bash
        - "-c"
        - |
          set -ex
          echo 'Starting init-mariadb';
          # Check config map to directory that already exists 
          # (but must be used as a volume for main container)
          ls /mnt/config-map
          # Statefulset has sticky identity, number should be last
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          # Copy appropriate conf.d files from config-map to 
          # mariadb-config volume (emptyDir) depending on pod number
          if [[ $ordinal -eq 0 ]]; then
            # This file holds SQL for connecting to primary
            cp /mnt/config-map/primary.cnf /etc/mysql/conf.d/server-id.cnf
            # Create the users needed for replication on primary on a volume
            # initdb (emptyDir)
            cp /mnt/config-map/primary-sts-0.sql /docker-entrypoint-initdb.d
            chmod 755 /docker-entrypoint-initdb.d/primary-sts-0.sql
          else
            # This file holds SQL for connecting to secondary
            cp /mnt/config-map/primary.cnf /etc/mysql/conf.d/server-id.cnf
            # On replicas use secondary configuration on initdb volume
            cp /mnt/config-map/primary-sts-1.sql /docker-entrypoint-initdb.d
            chmod 755 /docker-entrypoint-initdb.d/primary-sts-1.sql
          fi
          # Add an offset to avoid reserved server-id=0 value.
          echo server-id=$((3000 + $ordinal)) >> etc/mysql/conf.d/server-id.cnf
          ls /etc/mysql/conf.d/
          cat /etc/mysql/conf.d/server-id.cnf
        volumeMounts:
          - name: commondb-sts-config-map
            mountPath: /mnt/config-map
          - name: commondb-sts-config
            mountPath: /etc/mysql/conf.d/
          - name: initdb
            mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      containers:
      - name: commondb
        image: private.el:5000/mariadb:latest
        ports:
        - containerPort: 3306
          name: commondb-port
        env:
        # Using Secrets
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: commondb-sts-secret
              key: commondb-sts-root-password
        - name: MYSQL_INITDB_SKIP_TZINFO
          value: "1"
        - name: TZ
          value: Asia/Seoul
        # Mount volume from persistent volume claim
        volumeMounts:
        - name: pv-datadir
          mountPath: /var/lib/mysql/
        - name: commondb-sts-config
          mountPath: /etc/mysql/conf.d/
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: commondb-sts-config-map
        configMap:
          name: commondb-sts-configmap
          #defaultMode: 0544
      - name: commondb-sts-config
        emptyDir: {}
      - name: initdb
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: pv-datadir
      namespace: 5gc-commondb-sts
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "hostpath"
      resources:
        requests:
          storage: 10Gi
